package blizzard

// Note this is autogenerated from the response - it may need to be tidied up at some point as its fairly ugly.
type (
	Color struct {
		R float64 `json:"r"`
		G float64 `json:"g"`
		B float64 `json:"b"`
		A float64 `json:"a"`
	}

	Realm struct {
		Key struct {
			Href string `json:"href"`
		} `json:"key"`
		ID   int    `json:"id"`
		Slug string `json:"slug"`
	}

	MythicKeystoneProfile struct {
		Links struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
		} `json:"_links"`
		CurrentPeriod struct {
			Period struct {
				Key struct {
					Href string `json:"href"`
				} `json:"key"`
				ID int `json:"id"`
			} `json:"period"`
			BestRuns []struct {
				CompletedTimestamp int64 `json:"completed_timestamp"`
				Duration           int   `json:"duration"`
				KeystoneLevel      int   `json:"keystone_level"`
				KeystoneAffixes    []struct {
					Key struct {
						Href string `json:"href"`
					} `json:"key"`
					Name string `json:"name"`
					ID   int    `json:"id"`
				} `json:"keystone_affixes,omitempty"`
				Members []struct {
					Character struct {
						Name  string `json:"name"`
						ID    int    `json:"id"`
						Realm Realm  `json:"realm"`
					} `json:"character"`
					Specialization struct {
						Key struct {
							Href string `json:"href"`
						} `json:"key"`
						Name string `json:"name"`
						ID   int    `json:"id"`
					} `json:"specialization"`
					Race struct {
						Key struct {
							Href string `json:"href"`
						} `json:"key"`
						Name string `json:"name"`
						ID   int    `json:"id"`
					} `json:"race"`
					EquippedItemLevel int `json:"equipped_item_level"`
				} `json:"members"`
				Dungeon struct {
					Key struct {
						Href string `json:"href"`
					} `json:"key"`
					Name string `json:"name"`
					ID   int    `json:"id"`
				} `json:"dungeon"`
				IsCompletedWithinTime bool `json:"is_completed_within_time"`
				MythicRating          struct {
					Color  Color   `json:"color"`
					Rating float64 `json:"rating"`
				} `json:"mythic_rating"`
				MapRating struct {
					Color  Color   `json:"color"`
					Rating float64 `json:"rating"`
				} `json:"map_rating"`
			} `json:"best_runs"`
		} `json:"current_period"`
		Seasons []struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			ID int `json:"id"`
		} `json:"seasons"`
		Character struct {
			Key struct {
				Href string `json:"href"`
			} `json:"key"`
			Name  string `json:"name"`
			ID    int    `json:"id"`
			Realm Realm  `json:"realm"`
		} `json:"character"`
		CurrentMythicRating struct {
			Color  Color   `json:"color"`
			Rating float64 `json:"rating"`
		} `json:"current_mythic_rating"`
	}
)
